import type { Metadata } from "next";
import "./globals.css";
import { Prompt } from "next/font/google";
const prompt = Prompt({
  variable: "--font-prompt",
  subsets: ["latin", "thai"], // รองรับภาษาไทย
  weight: ["300", "400", "500", "700"], // เลือกน้ำหนักฟอนต์ที่ต้องการ
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${prompt.variable} ${prompt.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
